name: infobip_mobilemessaging
description: Infobip Mobile Messaging Flutter Plugin for Push notifications, LiveChat, and WebRTC calls.
version: 9.2.1
homepage: https://github.com/infobip/mobile-messaging-flutter-plugin#readme
repository: https://github.com/infobip/mobile-messaging-flutter-plugin
issue_tracker: https://github.com/infobip/mobile-messaging-flutter-plugin/issues

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  lints: ^2.1.1

flutter:
  plugin:
    platforms:
      android:
        package: org.infobip.plugins.mobilemessaging.flutter.infobip_mobilemessaging
        pluginClass: InfobipMobilemessagingPlugin
      ios:
        pluginClass: InfobipMobilemessagingPlugin
  assets:
    - pubspec.yaml
